# appveyor.yml - https://www.appveyor.com/docs/lang/python
# https://www.appveyor.com/docs/windows-images-software/#visual-studio-2022
---
image: Visual Studio 2022

environment:
  matrix:AppVeyor: Test on Python 3.8, 3.9, 3.10, 3.11, 3.12
    - TOXENV: py38    # https://devguide.python.org/versions
    - TOXENV: py39
    - TOXENV: py310
    - TOXENV: py311
    - TOXENV: py312

init:
  - py -VV
  - py -c "import struct;print( 8 * struct.calcsize(\'P\'))"
  - py --list  # What Python versions are installed?

install:
  - py -m pip install --upgrade pip
  - py -m pip install build tox wheel

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - py -m tox

after_test:
  - py -m build
  - ps: "ls dist"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
